# action.yml
name: 'Workflow Helper'
author: 'Tegonal GmbH, Switzerland'
description: 'Utility to manage your actual workflow (not as in github workflow)'
inputs:
  commands:
    description: 'specify which commands to execute (is fed into `bash -c`);'
    required: true
runs:
  using: 'docker'
  image: 'docker://tegonal/workflow-helper:v0.2.7'
  args:
    - ${{ inputs.commands }}
branding:
  icon: 'thermometer'
  color: 'green'