name: Cleanup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Format Sources
        run: sbt scalafmtAll scalafmtSbt
      - name: Update help snippets in README
        run: ./scripts/update-readme-help.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-cleanup
          title: Cleanup
          commit-message: cleanup sources
          body: Looks like someone forgot to run some commands before committing. I did it for them :)
          delete-branch: true